### ISSUE TITLE
Can't debug in vue-cli 3.0x/4.x webpack app

### ISSUE THREAD

**Issue by Akimotorakiyu** [firefox-devtools/vscode-firefox-debug#144]
The below configurations works well with debugger for chrome, but not works  with debugger for  firefox.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "vuejs: chrome",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}/src",
      "breakOnLoad": true,
      "sourceMapPathOverrides": {
        "webpack:///./src/*": "${webRoot}/*"
      }
    },
    {
      "type": "firefox",
      "request": "launch",
      "name": "vuejs: firefox",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}/src",
      "pathMappings": [{ "url": "webpack:///src/", "path": "${webRoot}/" }]
    }
  ]
}

```

https://github.com/vuejs/cn.vuejs.org/issues/1026

vue-cli : 4.0.4
vue : 2.6.10
language: typescript

firefox: 69.0.3

**Comment by hbenl** [comment]
I tried to create a vue cli app and could debug it with your configuration. What is the issue that you are seeing?
- do breakpoints remain gray (i.e. inactive)?
- are the breakpoints red, but the debugger doesn't break on them? In that case try to click the reload button in Firefox

**Comment by Akimotorakiyu** [comment]
The breakpoints red, but the debugger doesn't break on them, and then I try to click the reload button in Firefox , but it still not break on breakpoints .

**Comment by hbenl** [comment]
Thanks for the screenshot, that allowed me to reproduce the issue. I am currently rewriting the sourcemapping code in the extension (mostly to improve performance and support the [new UI for column breakpoints](https://code.visualstudio.com/updates/v1_39#_improved-ui-for-column-breakpoints)). It will become more similar to how Firefox' built-in debugger handles sourcemaps and since that works with this example, the rewrite should fix the issue.

**Comment by hbenl** [comment]
With the latest version (2.6.0) it works for me.
Please try with that version and tell me if it also works in your project now.

**Comment by Akimotorakiyu** [comment]
It still not works with debugger for firefox.

Should I change some configurations ?

**Comment by hbenl** [comment]
Could you share a sample project with which I can reproduce the issue?

**Comment by Akimotorakiyu** [comment]
@hbenl find the issue, now it works(need fresh page once more).
