### ISSUE TITLE
connect ECONNREFUSED ::1:6000

### ISSUE THREAD

**Issue by BuZZ-dEE** [firefox-devtools/vscode-firefox-debug#341]
https://stackoverflow.com/questions/77095858/vscode-debugger-sudden-econnrefused-error-cannot-connect-debugger-to-firefox

**Comment by SimpleProgrammingAU** [comment]
> Debugging with Firefox in VS Code suddenly stopped working on Windows, launching or attaching the debugger always results in error message connect ECONNREFUSED ::1:6000.
> 
> Tried deleting all VSCode related configuration and cache files and re-install latest VSCode in user mode, installed latest Firefox Developer Edition and tried debugging with default profile and non-persistent profile to see if the problem lies elsewhere.
> 
> Tried different debugger launch configurations.
> 
> None of this had any effect and problem still persists.

I'm also experiencing this issue.

When I used the same launch configuration but swapped `firefox` out for `chrome` via the Javascript Debugger extension. This might be a suitable stop-gap for you.

**Comment by alicedb2** [comment]
> PR #329 fixes it. had the same issue. since the last commit was over a year ago on this repo, i'd recommend pulling down the PR's author's fork or creating your own fork and pulling #329 in, building and installing from a local file via `Install from VSIX` vscode command

I have never built vs extensions from sources, could we get a quick rundown on building the vsix? I have node v20.7.0 and npm v10.1.0 installed. Here's what I tried to do:

```
git clone https://github.com/sorashi/vscode-firefox-debug
cd vscode-firefox-debug
git checkout node-17-fix
npm install
vsce package
```
but I get
```
 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/dist/extension.bundle.js
```

**Comment by alicedb2** [comment]
Just leaving this here for those of us who never built VS extensions from sources

```
git clone https://github.com/sorashi/vscode-firefox-debug
cd vscode-firefox-debug
git checkout node-17-fix
npm install
npm install original-fs
npm run build
vsce package
```
and now you can go ahead and install `vscode-firefox-debug-2.9.8.vsix`.

**Comment by hbenl** [comment]
Fixed in version 2.9.10.

**Comment by BuZZ-dEE** [comment]
> Fixed in version 2.9.10.

I can confirm it and close this issue.

**Comment by trysten** [comment]
@hbenl please update [open-vsx.org](https://open-vsx.org/extension/firefox-devtools/vscode-firefox-debug) to 2.9.10 :innocent: 
Appreciate you!

**Comment by ChocolatCoco** [comment]
Hello, I still have this exact same error. I allowed all the required things in about:config and this is my configuration file : 

        {
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "name": "Launch localhost",
            "url": "http://localhost:5500",
            "webRoot": "${workspaceFolder}",
        }

I am using the live server extension, after I launch the live server, I try to use the debuger however it makes the error 
"connect ECONNREFUSED ::1:6000"

I tried to add a "port":5500 in the config to see what happens and then it did "connect ECONNREFUSED ::1:5500"

I don't have google chrome installed by the way. I say that because on the firefox extension document it asks the people to activate a chrome related thing in about:config.

If someone has an idea on how to solve this it would be good

By the way I also noticed right now that my version is 2.9.1 and not 2.9.10, is it because of vs codium ?
How to install the 2.9.10 on codium ? I believe it's probably the problem. I really dont know how to do this
